---
- name: inetRouter | Config network
  hosts: inetRouter
  become: true
  vars:
    gateway: '192.168.255.2'
    network: '192.168.0.0/16'
  tasks:
    - name: inetRouter | Forwarding enable  
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes      

    - name: inetRouter | Create static route
      template: 
        src: ./templates/route-eth1.j2
        dest: /etc/sysconfig/network-scripts/route-eth1

    - name: restart network
      systemd:
        name: network
        state: restarted      

- name: centralRouter | Config network
  hosts: centralRouter
  vars:
    gateway: '192.168.255.1'
    ip: '192.168.255.2'   
  become: true

  tasks:
    - name: centralRouter | Forwarding enable  
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes      

    - name: centralRouter | Configure def gateway
      template:
        src: ./templates/ifcfg-eth1.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
 
    - name: centralServer | Configure gateway
      copy:
        src: ./templates/ifcfg-eth0
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0   

    - name: client | Accept port 80 tcp 
      iptables:
        table: nat
        chain: PREROUTING
        destination: "192.168.255.13"
        protocol: tcp
        destination_port: "80"
        jump: DNAT    
        to_destination: "192.168.0.2"
  
    - name: client | Accept port 80 tcp 
      iptables:
        table: nat
        chain: POSTROUTING
        destination: "192.168.0.2"
        protocol: tcp
        match: tcp
        destination_port: "80"
        jump: SNAT    
        to_source: "192.168.0.1"
  
    - name: client | Accept port 80 tcp 
      iptables:
        table: filter
        chain: FORWARD
        destination: "192.168.0.2"
        protocol: tcp
        match: tcp
        destination_port: "80"
        jump: ACCEPT    
  
    - name: client | Accept port 80 tcp 
      iptables:
        table: filter
        chain: FORWARD
        match: conntrack
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT  
  
    - name: restart network
      systemd:
        name: network
        state: restarted

- name: centralServer | Config network
  hosts: centralServer
  vars:
    network: '192.168.0.0/16'   
    gateway: '192.168.0.1'
    ip: '192.168.0.2'     
  become: true 

  tasks:  
    - name: centralServer | Install packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - nginx  


    - name: centralServer | Configure gateway
      copy:
        src: ./templates/ifcfg-eth0
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
       

    - name: centralServer | Configure gateway
      template:
        src: ./templates/ifcfg-eth1.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1

    - name: centralServer | Create static route
      template: 
        src: ./templates/route-eth1.j2
        dest: /etc/sysconfig/network-scripts/route-eth1
  
    - name: start nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: restart network
      systemd:
        name: network
        state: restarted

- name: inetRouter2 | Config network
  hosts: inetRouter2
  vars:
    gateway: '192.168.255.13'
    network: '192.168.0.0/16'    
    ip: '192.168.2.66'  
  become: true 

  tasks:  
    - name: inetRouter2 | Forwarding enable  
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes 
  
    - name: inetRouter2 | Create static route
      template: 
        src: ./templates/route-eth1.j2
        dest: /etc/sysconfig/network-scripts/route-eth1

    - name: client | Accept port 80 tcp 
      iptables:
        table: nat
        chain: PREROUTING
        protocol: tcp
        destination_port: "80"
        jump: DNAT    
        to_destination: "192.168.255.13"
  
    - name: client | Accept port 80 tcp 
      iptables:
        table: nat
        chain: POSTROUTING
        destination: "192.168.255.13"
        protocol: tcp
        match: tcp
        destination_port: "80"
        jump: SNAT    
        to_source: "192.168.255.14"
  
    - name: client | Accept port 80 tcp 
      iptables:
        table: filter
        chain: FORWARD
        destination: "192.168.255.14"
        protocol: tcp
        match: tcp
        destination_port: "80"
        jump: ACCEPT    
  
    - name: client | Accept port 80 tcp 
      iptables:
        table: filter
        chain: FORWARD
        match: conntrack
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT            
      
    - name: restart network
      systemd:
        name: network
        state: restarted      
  
